# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
    - container: windows1803
      image: microsoft/windowsservercore:1803

pool:
  vmImage: 'win1803'


container: windows1803

steps:

- script: |
    docker version
    docker pull python
  displayName: 'Run perf test'
